export const GET_HOSPITAL_REQ = "GET_HOSPITAL_REQ";
export const GET_HOSPITAL_SUC = "GET_HOSPITAL_SUC";
export const GET_HOSPITAL_FAIL = "GET_HOSPITAL_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CREATE_HOSPITAL_REQ = "CREATE_HOSPITAL_REQ";
export const CREATE_HOSPITAL_SUC = "CREATE_HOSPITAL_SUC";
export const CREATE_HOSPITAL_FAIL = "CREATE_HOSPITAL_FAIL";
export const CLEAR_ERRORS_HOSPITAL = "CLEAR_ERRORS_HOSPITAL";
export const HOSPITAL_DETAILS_REQ = "HOSPITAL_DETAILS_REQ";
export const HOSPITAL_DETAILS_SUC = "HOSPITAL_DETAILS_SUC";
export const HOSPITAL_DETAILS_FAIL = "HOSPITAL_DETAILS_FAIL";

export const UPDATE_HOSPITAL_REQ = "UPDATE_HOSPITAL_REQ";
export const UPDATE_HOSPITAL_SUC = "UPDATE_HOSPITAL_SUC";
export const UPDATE_HOSPITAL_FAIL = "UPDATE_HOSPITAL_FAIL";

export const CREATE_HOSPITAL_RESET = "CREATE_HOSPITAL_RESET";
export const UPDATE_HOSPITAL_RESET = "UPDATE_HOSPITAL_RESET";
