export const GET_HOSPITAL_REQ = "GET_HOSPITAL_REQ";
export const GET_HOSPITAL_SUC = "GET_HOSPITAL_SUC";
export const GET_HOSPITAL_FAIL = "GET_HOSPITAL_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
