export const GET_HOSPITAL_REQ = "GET_HOSPITAL_REQ";
export const GET_HOSPITAL_SUC = "GET_HOSPITAL_SUC";
export const GET_HOSPITAL_FAIL = "GET_HOSPITAL_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CREATE_HOSPITAL_REQ = "CREATE_HOSPITAL_REQ";
export const CREATE_HOSPITAL_SUC = "CREATE_HOSPITAL_SUC";
export const CREATE_HOSPITAL_FAIL = "CREATE_HOSPITAL_FAIL";
export const CLEAR_ERRORS_HOSPITAL = "CLEAR_ERRORS_HOSPITAL";

export const CREATE_HOSPITAL_RESET = "CREATE_HOSPITAL_RESET";
