export const GET_PATIENTS_REQ = "GET_PATIENTS_REQ";
export const GET_PATIENTS_SUC = "GET_PATIENTS_SUC";
export const GET_PATIENTS_FAIL = "GET_PATIENTS_FAIL";
export const PATIENT_DETAILS_REQ = "PATIENT_DETAILS_REQ";
export const PATIENT_DETAILS_SUC = "PATIENT_DETAILS_SUC";
export const PATIENT_DETAILS_FAIL = "PATIENT_DETAILS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
