export const GET_PATIENTS_REQ = "GET_PATIENTS_REQ";
export const GET_PATIENTS_SUC = "GET_PATIENTS_SUC";
export const GET_PATIENTS_FAIL = "GET_PATIENTS_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
